return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.bars-and-lines.vim-illuminate" },
  { import = "astrocommunity.colorscheme.catppuccin", enable = true },
  { import = "astrocommunity.colorscheme.gruvbox-nvim", enable = true },
  { import = "astrocommunity.colorscheme.gruvbox-baby", enable = true },
  { import = "astrocommunity.colorscheme.monokai-pro-nvim", enable = true },
  { import = "astrocommunity.colorscheme.kanagawa-nvim", enable = true },
  { import = "astrocommunity.colorscheme.tokyonight-nvim", enable = true },
  { import = "astrocommunity.colorscheme.vscode-nvim", enable = true },
  { import = "astrocommunity.colorscheme.nightfox-nvim", enable = true },
  { import = "astrocommunity.colorscheme.rose-pine", enable = true },
  { import = "astrocommunity.pack.bash" },
  { import = "astrocommunity.pack.cpp" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.python-ruff" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.pack.zig" },
  { import = "astrocommunity.motion.mini-surround" },
  { import = "astrocommunity.motion.leap-nvim" },
  { import = "astrocommunity.scrolling.mini-animate" },
  { import = "astrocommunity.utility.noice-nvim" },
}
